#!/bin/bash

echo "
______               _     _                       
| ___ \             (_)   (_)                      
| |_/ / __ _____   ___ ___ _  ___  _ __   ___ _ __ 
|  __/ '__/ _ \ \ / / / __| |/ _ \| '_ \ / _ \ '__|
| |  | | | (_) \ V /| \__ \ | (_) | | | |  __/ |   
\_|  |_|  \___/ \_/ |_|___/_|\___/|_| |_|\___|_|"

echo
echo
echo "Adding Vim 8.0 PPA"
add-apt-repository ppa:jonathonf/vim

echo
echo "Updating apt repos"
apt update

echo
echo "Installing Vim 8.0"
apt install vim -y

echo 
echo "Adding New User"
adduser --disabled-password --gecos "" yevgeny
echo "Adding New User to superuser group"
usermod -aG sudo yevgeny
echo "yevgeny ALL=(ALL) NOPASSWD:ALL" >>  /etc/sudoers #passwordless sudo

echo
echo "Installing NPM"
apt install npm -y

echo
echo "Installing N"
npm install -g n

echo
echo "Instaling Latest Node version"
n latest
npm --version
node --version

echo
echo "Installing Apache and Configuring"
apt install apache2 -y
a2dissite 000-default.conf
a2enmod proxy
a2enmod proxy_http
mkdir /var/www/bulochnik.com
echo "
<VirtualHost *:80>
    ServerName bulochnik.com
    DocumentRoot /var/www/bulochnik.com
</VirtualHost>" > /etc/apache2/sites-available/bulochnik.com.conf
echo "
<VirtualHost *:80>
    ServerName dev.bulochnik.com
    ProxyPreserveHost On
    ProxyPass / http://localhost:8181/
    ProxyPassReverse / http://localhost:8181/
</VirtualHost> " > /etc/apache2/sites-available/dev.bulochnik.com.conf
a2ensite bulochnik.com.conf
a2ensite dev.bulochnik.com.conf

echo
echo "Cloning dotfiles with https and setting symlinks"
su yevgeny <<Commands
git clone https://github.com/yevgenybulochnik/dotfiles.git ~/workspace/dotfiles
ln -s ~/workspace/dotfiles/.vimrc ~
ln -s ~/workspace/dotfiles/.gitconfig ~
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
Commands

su yevgeny -c "vim +PluginInstall +qall" #Note: command does run correctly in a heredoc

su yevgeny -c "git clone git://github.com/c9/core.git ~/c9sdk"

su yevgeny -c "~/c9sdk/scripts/install-sdk.sh*"
