#!/bin/bash

echo "
______               _     _                       
| ___ \             (_)   (_)                      
| |_/ / __ _____   ___ ___ _  ___  _ __   ___ _ __ 
|  __/ '__/ _ \ \ / / / __| |/ _ \| '_ \ / _ \ '__|
| |  | | | (_) \ V /| \__ \ | (_) | | | |  __/ |   
\_|  |_|  \___/ \_/ |_|___/_|\___/|_| |_|\___|_|"

echo
echo
echo "Updating apt repos"
apt update

echo 
echo 
echo "Adding New User"
useradd -m  yevgeny "-m creates a user directory in home/" 
echo "Adding New User to superuser group"
usermod -aG sudo yevgeny
